#!/bin/bash

# Usage: 
# bash path/to/script/DS_vcf2maf myConfig.csv my_species my_ncbi_build my_vep_version
#
# Example:
# bash DS_vcf2maf myConfig.csv homo_sapiens GRCh38 99
# 
# Be sure you've set up your VCF2MAF_progConfig.yaml to your machine

myLoc=$(dirname $0)
# This is a run script to make MAF files from 
# output DS VCFs
inDir="$1"
runBarcode="$2"
outPrefix="$3"
snakemake -s ${myLoc}/Snakefile \
--keep-going \
--use-conda \
--conda-prefix ${myLoc}/.snakemake \
-j 12 \
--dag \
--config in_dir="${inDir}" \
run_barcode="${runBarcode}" \
out_prefix="${outPrefix}" \
-- | dot -Tpdf > ${outPrefix}_picardDemux_dag.pdf